name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 3.0.100
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v1
    - name: Build and test on macOS and Ubuntu
      run: |
        chmod +x ci.sh
        ./ci.sh
      shell: bash
      if: matrix.os == 'macOS-latest' || matrix.os == 'ubuntu-latest'
    - name: Build and test on Windows
      run: ./ci.ps1
      shell: powershell
      if: matrix.os == 'windows-latest'
    - name: Upload Code Coverage to codecov.io from macOS
      run: |
        curl -s https://codecov.io/bash > codecov
        chmod +x codecov
        ./codecov -f "./CoverageResults/coverage.opencover.xml" -t ${{ secrets.CODECOV_TOKEN }}
      shell: bash
      if: matrix.os == 'macOS-latest'
    - name: Publish to NuGet from Ubuntu
      run: |
        chmod +x pack.sh
        ./pack.sh
        nuget push ./nupkgs/*.nupkg -ApiKey ${{ secrets.NUGET_KEY }}
      shell: bash
      if: matrix.os == 'ubuntu-latest'
      
