name: Release

on:
  release:
    types: [published]
  
jobs:
  build_test_release:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: ./ci.ps1
      shell: powershell
    - name: Create NuGet-package
      run: ./pack.ps1
      shell: powershell
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Push to NuGet
      run: nuget push nupkgs\NotifyPropertyChanged.Verifier.nupkg -Source https://www.nuget.org/api/v2/package -ApiKey ${{ secrets.NUGET_KEY }}
    - name: Add GPR Source
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/Sankra/index.json -Username Sankra -Password ${{ secrets.GITHUB_TOKEN }}
    - name: Push to GPR
      run: nuget push nupkgs\NotifyPropertyChanged.Verifier.nupkg -Source "GPR" -SkipDuplicate
