name: Release

on:
  release:
    types: [published]
  
jobs:
  build_test_release:

    runs-on: macOS-latest
    
    steps:
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: '3.1.x'
      if: matrix.os == 'macOS-latest'
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
        chmod +x ci.sh
        ./ci.sh
      shell: bash
    - name: Publish to NuGet
      run: |
        chmod +x pack.sh
        ./pack.sh
        nuget push ./nupkgs/*.nupkg -Source https://www.nuget.org/api/v2/package -ApiKey ${{ secrets.NUGET_KEY }}
        #nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/Sankra/index.json -Username Sankra -Password ${{ secrets.GITHUB_TOKEN }}
        #nuget push ./nupkgs/*.nupkg -Source "GPR"
      shell: bash
      
